### ISSUE TITLE
Can not copy to clipboard

### ISSUE THREAD

**Issue by matthiaskern** [jsantiagoh/cerebro-pass#3]
Entries show up correctly but when selected, nothing is copied.
Executing a file like below however works correctly. Any ideas?
I'm on mac and gpgagent is using mac keychain
```js
const exec = require('child_process').exec;

exec('pass -c example.com');
```

**Comment by jsantiagoh** [comment]
Hi, at the moment I don't have a mac nearby to try it, sorry.

**Comment by max-baz** [comment]
Hey @matthiaskern, do you still experience the issue?

I've just released v1.0.0, could you try to reproduce it on the new version? Also have a look in the cerebro console to see if there are some errors (I added more error logging) by enabling "Developer mode" in cerebro settings and then right clicking on tray icon > Development > DevTools (main).

**Comment by matthiaskern** [comment]
@maximbaz 
Local version linked via `npm run debug` is working now. Thank you!

When installed directly from cerebro the following error happens:
```
Error running plugin cerebro-pass ReferenceError: action is not defined
    at Object.parse (/Users/test/Library/Application Support/Cerebro/plugins/node_modules/cerebro-pass/dist/index.js:1:21954)
    at Object.fn (/Users/test/Library/Application Support/Cerebro/plugins/node_modules/cerebro-pass/dist/index.js:1:21284)
    at Object.keys.forEach.n (file:///Applications/Cerebro.app/Contents/Resources/app.asar/dist/main.bundle.js:1:756646)
    at Array.forEach (native)
    at p (file:///Applications/Cerebro.app/Contents/Resources/app.asar/dist/main.bundle.js:1:756620)
    at t (file:///Applications/Cerebro.app/Contents/Resources/app.asar/dist/main.bundle.js:1:757018)
    at file:///Applications/Cerebro.app/Contents/Resources/app.asar/dist/main.bundle.js:1:719061
    at Object.onChange (file:///Applications/Cerebro.app/Contents/Resources/app.asar/dist/main.bundle.js:1:719886)
    at onChange (file:///Applications/Cerebro.app/Contents/Resources/app.asar/dist/main.bundle.js:1:772802)
    at Object.executeOnChange (file:///Applications/Cerebro.app/Contents/Resources/app.asar/dist/main.bundle.js:1:127500)
```

I'm guessing this is a transpilation issue and babili can be configured to fix this.

**Comment by max-baz** [comment]
Argh, I thought I got rid of that issue - thanks I'll look into it soon!

**Comment by max-baz** [comment]
I went for the same solution as in https://github.com/KELiON/cerebro/pull/335, which is replacing babili with uglify-es. Looks like v1.0.1 finally works 🙂 Can you confirm?

**Comment by matthiaskern** [comment]
Works like a charm :tada:

**Comment by benreyn** [comment]
I am still having this issue on Version 1.0.4 on macOS Sierra.

**Comment by benreyn** [comment]
Nevermind the above ^ I upgraded Cerebro to Version 0.3 and all is working fine now
